using System.Threading;
// ReSharper disable StaticMemberInGenericType

namespace BIG.ECS
{
    /// <summary>
    /// Interface for every component in ECS system.
    /// IMPORTANT - each implementation needs to be a struct.
    /// </summary>
    public interface IComponent { }

    /// <summary>
    /// Used to generate unique IDs for components at compile time.
    /// </summary>
    public static class ComponentId<T> where T : struct, IComponent
    {
        /// <summary>
        /// Static readonly value that is assigned to each component type at compile time. It is generated by incrementing a static counter for each new component type.
        /// </summary>
        public static readonly int Value = ComponentId.Next();
    }

    static class ComponentId
    {
        private static int _next;
        public static int Next() => Interlocked.Increment(ref _next) - 1;
    }

    /// <summary>
    /// Used to store collection of components by their type.
    /// </summary>
    public static class Components<T> where T : struct, IComponent
    {
        private static readonly T[] COMPONENTS;
        static Components()
        {
            COMPONENTS = new T[10_000_000];
        }

        /// <summary>
        /// Get reference to component of type T by its ID.
        /// </summary>
        /// <param name="id">Entity id.</param>
        /// <returns>Reference to the component that we want to read/write.</returns>
        public static ref T Get(int id) => ref COMPONENTS[id];

        /// <summary>
        /// Assigns the specified component to the collection at the given entity.
        /// </summary>
        /// <param name="id">Entity id.</param>
        /// <param name="component">The component to assign.</param>
        public static void Set(int id, T component) => COMPONENTS[id] = component;
    }

    /// <summary>
    /// Extension method for components that handle flags making sure that we understand which components are attached to which entity.
    /// </summary>
    public static class ComponentsUtils
    {
        /// <summary>
        /// For every entity we maintain a list of components attached to it in a form of enum flags.
        /// Every time we are adding a component to entity we are calling this function.
        /// It is used by <see cref="EntityManager"/>.
        /// </summary>
        /// <param name="components"><see cref="Entity.Components"/> ulong value that store all the components attached to the entity in a form of enum flags.</param>
        /// <typeparam name="T">Type of component that <see cref="EntityManager"/> want to add to the entity.</typeparam>
        public static void AddFlag<T>(this ref ulong components) where T : struct, IComponent
        {
            components |= 1UL << ComponentId<T>.Value;
        }

        /// <summary>
        /// For every entity we maintain a list of components attached to it in a form of enum flags.
        /// Every time we are removing a component from entity we are calling this function.
        /// It is used by <see cref="EntityManager"/>.
        /// </summary>
        /// <param name="components"><see cref="Entity.Components"/> ulong value that store all the components attached to the entity in a form of enum flags.</param>
        /// <typeparam name="T">Type of <see cref="IComponent"/> implementation we want to remove from this entity.</typeparam>
        public static void RemoveFlag<T>(this ref ulong components) where T : struct, IComponent
        {
            components &= ~(1UL << ComponentId<T>.Value);
        }

        /// <summary>
        /// Check if given <see cref="Entity.Components"/> ulong value has a flag for component of type T.
        /// </summary>
        /// <param name="components"><see cref="Entity.Components"/></param>
        /// <typeparam name="T">Type of <see cref="IComponent"/> implementation that we want to check.</typeparam>
        /// <returns>Value indicating whether given <see cref="Entity.Components"/> have a component of a given type.</returns>
        public static bool HasFlag<T>(this ulong components) where T : struct, IComponent
        {
            return (components & (1UL << ComponentId<T>.Value)) != 0;
        }
    }
}
